/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCreateGigRouteImport } from './routes/_authenticated/create-gig'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEarningsRouteImport } from './routes/_authenticated/earnings'
import { Route as AuthenticatedGigsRouteImport } from './routes/_authenticated/gigs'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedMessagesRouteRouteImport } from './routes/_authenticated/messages/route'
import { Route as AuthenticatedMyGigsRouteImport } from './routes/_authenticated/my-gigs'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSellRouteRouteImport } from './routes/_authenticated/sell/route'
import { Route as AuthenticatedHelpersHelperIdRouteImport } from './routes/_authenticated/helpers/$helperId'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages/index'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages/$conversationId'
import { Route as AuthenticatedSellIndexRouteImport } from './routes/_authenticated/sell/index'
import { Route as AuthenticatedSellCreateRouteImport } from './routes/_authenticated/sell/create'
import { Route as AuthenticatedServiceListingsIndexRouteImport } from './routes/_authenticated/service-listings/index'
import { Route as AuthenticatedServiceListingsIdRouteImport } from './routes/_authenticated/service-listings/$id'
import { Route as AuthenticatedSellEditIdRouteImport } from './routes/_authenticated/sell/edit/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateGigRoute = AuthenticatedCreateGigRouteImport.update({
  id: '/create-gig',
  path: '/create-gig',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEarningsRoute = AuthenticatedEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGigsRoute = AuthenticatedGigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRouteRoute =
  AuthenticatedMessagesRouteRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyGigsRoute = AuthenticatedMyGigsRouteImport.update({
  id: '/my-gigs',
  path: '/my-gigs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellRouteRoute = AuthenticatedSellRouteRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpersHelperIdRoute =
  AuthenticatedHelpersHelperIdRouteImport.update({
    id: '/helpers/$helperId',
    path: '/helpers/$helperId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMessagesRouteRoute,
  } as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedMessagesRouteRoute,
  } as any)
const AuthenticatedSellIndexRoute = AuthenticatedSellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSellRouteRoute,
} as any)
const AuthenticatedSellCreateRoute = AuthenticatedSellCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedSellRouteRoute,
} as any)
const AuthenticatedServiceListingsIndexRoute =
  AuthenticatedServiceListingsIndexRouteImport.update({
    id: '/service-listings/',
    path: '/service-listings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServiceListingsIdRoute =
  AuthenticatedServiceListingsIdRouteImport.update({
    id: '/service-listings/$id',
    path: '/service-listings/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSellEditIdRoute = AuthenticatedSellEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AuthenticatedSellRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof AuthenticatedMessagesRouteRouteWithChildren
  '/sell': typeof AuthenticatedSellRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/create-gig': typeof AuthenticatedCreateGigRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/gigs': typeof AuthenticatedGigsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/my-gigs': typeof AuthenticatedMyGigsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/helpers/$helperId': typeof AuthenticatedHelpersHelperIdRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/sell/create': typeof AuthenticatedSellCreateRoute
  '/service-listings/$id': typeof AuthenticatedServiceListingsIdRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/sell/': typeof AuthenticatedSellIndexRoute
  '/service-listings/': typeof AuthenticatedServiceListingsIndexRoute
  '/sell/edit/$id': typeof AuthenticatedSellEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/create-gig': typeof AuthenticatedCreateGigRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/gigs': typeof AuthenticatedGigsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/my-gigs': typeof AuthenticatedMyGigsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/helpers/$helperId': typeof AuthenticatedHelpersHelperIdRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/sell/create': typeof AuthenticatedSellCreateRoute
  '/service-listings/$id': typeof AuthenticatedServiceListingsIdRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/sell': typeof AuthenticatedSellIndexRoute
  '/service-listings': typeof AuthenticatedServiceListingsIndexRoute
  '/sell/edit/$id': typeof AuthenticatedSellEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteRouteWithChildren
  '/_authenticated/sell': typeof AuthenticatedSellRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/create-gig': typeof AuthenticatedCreateGigRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/earnings': typeof AuthenticatedEarningsRoute
  '/_authenticated/gigs': typeof AuthenticatedGigsRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/my-gigs': typeof AuthenticatedMyGigsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/helpers/$helperId': typeof AuthenticatedHelpersHelperIdRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/sell/create': typeof AuthenticatedSellCreateRoute
  '/_authenticated/service-listings/$id': typeof AuthenticatedServiceListingsIdRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/sell/': typeof AuthenticatedSellIndexRoute
  '/_authenticated/service-listings/': typeof AuthenticatedServiceListingsIndexRoute
  '/_authenticated/sell/edit/$id': typeof AuthenticatedSellEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/messages'
    | '/sell'
    | '/admin'
    | '/create-gig'
    | '/dashboard'
    | '/earnings'
    | '/gigs'
    | '/inbox'
    | '/marketplace'
    | '/my-gigs'
    | '/onboarding'
    | '/profile'
    | '/helpers/$helperId'
    | '/messages/$conversationId'
    | '/sell/create'
    | '/service-listings/$id'
    | '/messages/'
    | '/sell/'
    | '/service-listings/'
    | '/sell/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/create-gig'
    | '/dashboard'
    | '/earnings'
    | '/gigs'
    | '/inbox'
    | '/marketplace'
    | '/my-gigs'
    | '/onboarding'
    | '/profile'
    | '/helpers/$helperId'
    | '/messages/$conversationId'
    | '/sell/create'
    | '/service-listings/$id'
    | '/messages'
    | '/sell'
    | '/service-listings'
    | '/sell/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/messages'
    | '/_authenticated/sell'
    | '/_authenticated/admin'
    | '/_authenticated/create-gig'
    | '/_authenticated/dashboard'
    | '/_authenticated/earnings'
    | '/_authenticated/gigs'
    | '/_authenticated/inbox'
    | '/_authenticated/marketplace'
    | '/_authenticated/my-gigs'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/helpers/$helperId'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/sell/create'
    | '/_authenticated/service-listings/$id'
    | '/_authenticated/messages/'
    | '/_authenticated/sell/'
    | '/_authenticated/service-listings/'
    | '/_authenticated/sell/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-gig': {
      id: '/_authenticated/create-gig'
      path: '/create-gig'
      fullPath: '/create-gig'
      preLoaderRoute: typeof AuthenticatedCreateGigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/earnings': {
      id: '/_authenticated/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AuthenticatedEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gigs': {
      id: '/_authenticated/gigs'
      path: '/gigs'
      fullPath: '/gigs'
      preLoaderRoute: typeof AuthenticatedGigsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-gigs': {
      id: '/_authenticated/my-gigs'
      path: '/my-gigs'
      fullPath: '/my-gigs'
      preLoaderRoute: typeof AuthenticatedMyGigsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell': {
      id: '/_authenticated/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof AuthenticatedSellRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/helpers/$helperId': {
      id: '/_authenticated/helpers/$helperId'
      path: '/helpers/$helperId'
      fullPath: '/helpers/$helperId'
      preLoaderRoute: typeof AuthenticatedHelpersHelperIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedMessagesRouteRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRouteRoute
    }
    '/_authenticated/sell/': {
      id: '/_authenticated/sell/'
      path: '/'
      fullPath: '/sell/'
      preLoaderRoute: typeof AuthenticatedSellIndexRouteImport
      parentRoute: typeof AuthenticatedSellRouteRoute
    }
    '/_authenticated/sell/create': {
      id: '/_authenticated/sell/create'
      path: '/create'
      fullPath: '/sell/create'
      preLoaderRoute: typeof AuthenticatedSellCreateRouteImport
      parentRoute: typeof AuthenticatedSellRouteRoute
    }
    '/_authenticated/service-listings/': {
      id: '/_authenticated/service-listings/'
      path: '/service-listings'
      fullPath: '/service-listings/'
      preLoaderRoute: typeof AuthenticatedServiceListingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service-listings/$id': {
      id: '/_authenticated/service-listings/$id'
      path: '/service-listings/$id'
      fullPath: '/service-listings/$id'
      preLoaderRoute: typeof AuthenticatedServiceListingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sell/edit/$id': {
      id: '/_authenticated/sell/edit/$id'
      path: '/edit/$id'
      fullPath: '/sell/edit/$id'
      preLoaderRoute: typeof AuthenticatedSellEditIdRouteImport
      parentRoute: typeof AuthenticatedSellRouteRoute
    }
  }
}

interface AuthenticatedMessagesRouteRouteChildren {
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedMessagesRouteRouteChildren: AuthenticatedMessagesRouteRouteChildren =
  {
    AuthenticatedMessagesConversationIdRoute:
      AuthenticatedMessagesConversationIdRoute,
    AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  }

const AuthenticatedMessagesRouteRouteWithChildren =
  AuthenticatedMessagesRouteRoute._addFileChildren(
    AuthenticatedMessagesRouteRouteChildren,
  )

interface AuthenticatedSellRouteRouteChildren {
  AuthenticatedSellCreateRoute: typeof AuthenticatedSellCreateRoute
  AuthenticatedSellIndexRoute: typeof AuthenticatedSellIndexRoute
  AuthenticatedSellEditIdRoute: typeof AuthenticatedSellEditIdRoute
}

const AuthenticatedSellRouteRouteChildren: AuthenticatedSellRouteRouteChildren =
  {
    AuthenticatedSellCreateRoute: AuthenticatedSellCreateRoute,
    AuthenticatedSellIndexRoute: AuthenticatedSellIndexRoute,
    AuthenticatedSellEditIdRoute: AuthenticatedSellEditIdRoute,
  }

const AuthenticatedSellRouteRouteWithChildren =
  AuthenticatedSellRouteRoute._addFileChildren(
    AuthenticatedSellRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMessagesRouteRoute: typeof AuthenticatedMessagesRouteRouteWithChildren
  AuthenticatedSellRouteRoute: typeof AuthenticatedSellRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCreateGigRoute: typeof AuthenticatedCreateGigRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEarningsRoute: typeof AuthenticatedEarningsRoute
  AuthenticatedGigsRoute: typeof AuthenticatedGigsRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedMyGigsRoute: typeof AuthenticatedMyGigsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedHelpersHelperIdRoute: typeof AuthenticatedHelpersHelperIdRoute
  AuthenticatedServiceListingsIdRoute: typeof AuthenticatedServiceListingsIdRoute
  AuthenticatedServiceListingsIndexRoute: typeof AuthenticatedServiceListingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMessagesRouteRoute: AuthenticatedMessagesRouteRouteWithChildren,
  AuthenticatedSellRouteRoute: AuthenticatedSellRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCreateGigRoute: AuthenticatedCreateGigRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEarningsRoute: AuthenticatedEarningsRoute,
  AuthenticatedGigsRoute: AuthenticatedGigsRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedMyGigsRoute: AuthenticatedMyGigsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedHelpersHelperIdRoute: AuthenticatedHelpersHelperIdRoute,
  AuthenticatedServiceListingsIdRoute: AuthenticatedServiceListingsIdRoute,
  AuthenticatedServiceListingsIndexRoute:
    AuthenticatedServiceListingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
